= Documentation testing

Instead of writing tests, we just writing documentation from the code.

Each test method is a documentation generator that not indicate expected result but just write the result.

The user has to validate documentation produced and make it the now the expected output.
When documentation changed, test fails and the user needs to validate or not this new behavior.

The advantage is that we not have to check the expected result in tests.
If the result we see in documentation is right, that's ok.
The second advantage is that we focus on documentation so that all our tests are readable by every one.

This idea comes from writing some code that is only configuration.
In that case, writing tests is just rewriting code and there is no real value.
But, this information still needs to be checked.

== Quick start

Start by writing a test that inherits from `org.sfvl.doctesting.ApprovalsBase`.

Use `ẁrite` method to write all you want to be in documentation.
It should be at least input and output.
When you write output, you don't write values expected but only values given by the application.

Then run test as usual.
First time, test fails and a file is produced in `src/test/docs` with the name of the test.
The filename ends with `received.adoc`.

Read the file and verify that it says what we expected.
If it is the case, rename it with `approved.adoc` instead of `received.adoc`.


[source, java]
.Example with DemoTest.java
----
include::src/test/java/org/sfvl/application/demo/DemoTest.java[]
----

|===
| File generated
a| include::src/test/docs/org/sfvl/application/demo/DemoTest.should_be_5_when_adding_2_and_3.approved.adoc[]
|===

== Generate a full documentation

To generate a single file with all tests, launch `MainDocumentation` class.

`convertAdoc.sh` takes the single generated file to convert it to HTML.

You can use `RunAll` class to make all process in a single command.
launch tests, generate an asciidoc with all files generated and convert it to HTML.

If you decide to change style of the documentation generated, all your tests will be failed.
You can approve them all using `approveAll.sh`.


