= Performance

We evaluate performance using different approaches.

This comparison is very light and approximate.
It's just to give an idea of the cost to generate files and compare them.

We show below time to execute different types of tests.
First, we execute a very simple test with JUnit, Approvals and using Git.
With Git, we execute it with option no-assert or not.
This option, is used when we launch tests with script to check failure only at the end.

We show what each test provide as output to compare a classical test to the approach based on the documentation.
With Junit, we just display test source code.

We see a factor of 7 between JUnit and Git.
In fact, there is a time taken to build JavaProjectBuilder to be able to parse code and retrieve comments.
This initialization finished, tests are pretty fast with a factor of 3 with JUnit.
With Approvals, preformance is less good (but may be optimized).
This approach is clearly slower than using Junit, but difference is not really signifiant unless there is a lot a tests.
We execute 1000 tests in less than 1 second.


