# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
    fail-fast: false
    matrix:
      java: ['8', '11']
      os: [ ubuntu, windows ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file documentationtesting/pom.xml
#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn --batch-mode deploy --file documentationtesting/pom.xml
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
