name: Publish and Release
# V1.0
on:
  push:
    branches: [ ci_workflow ]
#  pull_request:
#    branches: [ develop ]
#    branches: [ master ]

  workflow_dispatch:

env:
  root_branch: 'ci_workflow'
  doc_branch: 'pages'
  docs_generated: 'docs'
  docs_published: 'published_docs'

jobs:
  merge_from_root_branch:
    name: Merge from root branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{env.doc_branch}}

      - name: Configure Git user
        run: |
          git config user.email "actions@noreply.github.com"
          git config user.name "GitHub Actions"

      - name: Merge from root branch
        run: |
          git merge origin/${{env.root_branch}} --allow-unrelated-histories -m "Merge root branch"
          git push -f
#        run: git merge origin/develop --allow-unrelated-histories -m "Merge from develop"
#        run: git merge origin/master --allow-unrelated-histories -m "Merge from master"

  generate_doc:
    name: Generate doc
    needs: merge_from_root_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.doc_branch}}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Package with Maven
#        run: mvn -B package --file documentationtesting/pom.xml
        run: |
          mkdir -p ${{env.docs_published}}
          echo "<html>My new doc</html>" > ${{env.docs_published}}/index.html

      - name: Copy docs
        run: |
          rm -Rf ${{env.docs_published}}
          cp -R ${{env.docs_generated}} ${{env.docs_published}}
#          rm -Rf docs
#          cp -R target/docs docs
#
      - name: Retrieve diff
        id: git_diff
        run: |
          git add ${{env.docs_published}}
          echo "::set-output name=DOC_DIFF::$(git diff --cached  | wc -l)"
#
      - name: Configure Git user
        if: steps.git_diff.outputs.DOC_DIFF > 0
        run: |
          git config user.email "actions@noreply.github.com"
          git config user.name "GitHub Actions"

      - name: Commit docs
        if: steps.git_diff.outputs.DOC_DIFF > 0
        run: |
          git add ${{env.docs_published}}
          git commit -m "New doc"
          git push -f
