# This is a basic workflow to help you get started with Actions
# https://github.com/marketplace/actions/maven-release
name: Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    #- name: Build and Test
    #    uses: qcastel/github-actions-maven-cmd@master
    #    run: mvn -B package --file documentationtesting/pom.xml
    - name: Publish JAR
        run: mvn -B release:prepare release:perform --file documentationtesting/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #- name: Release
    #    uses: qcastel/github-actions-maven-release@master
    #    with:
    #      maven-project-folder: documentationtesting
    #      version-minor: true
    #      access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    #